# Generated by Django 3.2.12 on 2022-03-07 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name of Ship")),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ship length in meter",
                        max_digits=5,
                        verbose_name="Length",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ship width in meter",
                        max_digits=5,
                        verbose_name="Width",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[A-Z]{4}-[0-9]{4}-[A-Z][0-9]$",
                                message="Code does not meet following regex [A-Z]{4}-[0-9]{4}-[A-Z][0-9]$",
                            )
                        ],
                        verbose_name="Unique Ship Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship",
                "verbose_name_plural": "Ships",
            },
        ),
    ]
