# Generated by Django 3.2.12 on 2022-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ship_manager", "0003_auto_20220304_1844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
