# Generated by Django 3.2.12 on 2022-03-05 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ship_manager", "0004_auto_20220304_2146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="code",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "[A-Z]{4}-[0-9]{4}-[A-Z][0-9]$",
                        message="Code does not meet following regex [A-Z]{4}-[0-9]{4}-[A-Z][0-9]$",
                    )
                ],
                verbose_name="Unique Ship Code",
            ),
        ),
    ]
